<?php

use App\Kernel;
use Symfony\Component\HttpFoundation\Request;

require dirname(__DIR__).'/vendor/autoload.php';

// Classic front controller (not symfony/runtime's auto-bootstrap): Composer
// disables plugins when running as root without COMPOSER_ALLOW_SUPERUSER=1
// (Railpack's fixed `composer install` never sets it), so
// vendor/autoload_runtime.php -- itself generated by symfony/runtime's own
// Composer plugin -- never exists in this build. This pattern only needs
// Composer's standard autoloader, always present regardless of plugins.
$kernel = new Kernel($_SERVER['APP_ENV'] ?? 'prod', (bool) ($_SERVER['APP_DEBUG'] ?? false));
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
